# Generated by Django 3.2.14 on 2022-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='league',
            field=models.CharField(choices=[(1, 'Первая лига'), (2, 'Вторая лига'), (3, 'Третья лига')], default=1, max_length=10, verbose_name='лига'),
        ),
    ]
