# Generated by Django 3.2.14 on 2022-07-23 17:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='название')),
                ('colour', models.CharField(choices=[('dark', 'темный'), ('light', 'светлый')], max_length=5, verbose_name='цвет')),
                ('least_permitted_league', models.CharField(choices=[(1, 'Первая лига'), (2, 'Вторая лига'), (3, 'Третья лига')], max_length=10, verbose_name='наименьшая разрешенная лига')),
                ('width', models.PositiveIntegerField(verbose_name='ширина')),
                ('heigth', models.PositiveIntegerField(verbose_name='высота')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='список тегов, разделенных запятыми', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'пак',
                'verbose_name_plural': 'паки',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='', verbose_name='превью')),
            ],
            options={
                'verbose_name': 'шаблон',
                'verbose_name_plural': 'шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftmost_coordinate', models.PositiveIntegerField(verbose_name='координаты левой стороны')),
                ('uppermost_coordinate', models.PositiveIntegerField(verbose_name='координаты верхней стороны')),
                ('rightmost_coordinate', models.PositiveIntegerField(verbose_name='координаты правой стороны')),
                ('lowermost_coordinate', models.PositiveIntegerField(verbose_name='координаты нижней стороны')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='templates.pack', verbose_name='пак')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='templates.template', verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'часть шаблона',
                'verbose_name_plural': 'части шаблона',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='изображение')),
                ('packs', models.ManyToManyField(blank=True, related_name='items', to='templates.Pack', verbose_name='пак')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='список тегов, разделенных запятыми', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'элементы',
            },
        ),
    ]
