version: "3.8"

services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB-constricon}
      POSTGRES_USER: ${POSTGRES_USER-constricon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBep9Frut}

  backend:
    build: backend
    image: app_backend
    volumes:
      - static_data:/static
      - ./backend:/code
    environment:
      SECRET_KEY: ${SECRET_KEY-REPLACE_ME}
      DEBUG: ${DEBUG-TRUE}
      DATABASE_URL: ${DATABASE_URL-postgres://constricon:OwOtBep9Frut@db:5432/constricon}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS-127.0.0.1,localhost}
    ports:
      - 8080:8080
    depends_on:
      - db
    command:
      python manage.py runserver 0.0.0.0:8080

volumes:
  db_data:
  static_data:
