version: "3.8"

services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB-constricon}
      POSTGRES_USER: ${POSTGRES_USER-constricon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBep9Frut}

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/constricon
    command:
      python manage.py runserver 0.0.0.0:8080
    env_file:
      - .env
      - .env.example
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db_data:
