# Generated by Django 3.2.14 on 2022-07-23 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='', verbose_name='превью')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='список тегов, разделенных запятыми', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='теги')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icons', to='templates.template', verbose_name='шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'иконка',
                'verbose_name_plural': 'иконки',
            },
        ),
        migrations.CreateModel(
            name='IconPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_items', to='icons.icon', verbose_name='иконка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_items', to='templates.item', verbose_name='элемент')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_items', to='templates.part', verbose_name='часть шаблона')),
            ],
            options={
                'verbose_name': 'часть иконки',
                'verbose_name_plural': 'части иконки',
            },
        ),
    ]
